USE [master]
GO
/****** Object:  Database [StockAccounts]    Script Date: 26.10.2023 г. 16:51:56 ******/
CREATE DATABASE [StockAccounts]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StockAccounts', FILENAME = N'C:\Users\HP\StockAccounts.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StockAccounts_log', FILENAME = N'C:\Users\HP\StockAccounts_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [StockAccounts] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockAccounts].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [StockAccounts] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [StockAccounts] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [StockAccounts] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [StockAccounts] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [StockAccounts] SET ARITHABORT OFF 
GO
ALTER DATABASE [StockAccounts] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [StockAccounts] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [StockAccounts] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [StockAccounts] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [StockAccounts] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [StockAccounts] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [StockAccounts] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [StockAccounts] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [StockAccounts] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [StockAccounts] SET  ENABLE_BROKER 
GO
ALTER DATABASE [StockAccounts] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [StockAccounts] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [StockAccounts] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [StockAccounts] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [StockAccounts] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [StockAccounts] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [StockAccounts] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [StockAccounts] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [StockAccounts] SET  MULTI_USER 
GO
ALTER DATABASE [StockAccounts] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [StockAccounts] SET DB_CHAINING OFF 
GO
ALTER DATABASE [StockAccounts] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [StockAccounts] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [StockAccounts] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [StockAccounts] SET QUERY_STORE = OFF
GO
USE [StockAccounts]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [StockAccounts]
GO
/****** Object:  Table [dbo].[Stock]    Script Date: 26.10.2023 г. 16:51:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stock](
	[Id] [varchar](36) NOT NULL,
	[StockName] [varchar](20) NULL,
	[Quantity] [int] NOT NULL,
	[WalletId] [varchar](36) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[StockName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transaction]    Script Date: 26.10.2023 г. 16:51:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transaction](
	[Id] [varchar](36) NOT NULL,
	[TotalAmount] [decimal](4, 2) NULL,
	[Quantity] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[IsSuccessful] [bit] NOT NULL,
	[StockId] [varchar](36) NULL,
	[WalletId] [varchar](36) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 26.10.2023 г. 16:51:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [varchar](36) NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[PasswordHash] [text] NOT NULL,
	[FirstName] [varchar](50) NULL,
	[LastName] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UserName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Wallet]    Script Date: 26.10.2023 г. 16:51:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Wallet](
	[Id] [varchar](36) NOT NULL,
	[Balance] [decimal](4, 2) NOT NULL,
	[UserId] [varchar](36) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Stock]  WITH CHECK ADD FOREIGN KEY([WalletId])
REFERENCES [dbo].[Wallet] ([Id])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD FOREIGN KEY([StockId])
REFERENCES [dbo].[Stock] ([Id])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD FOREIGN KEY([WalletId])
REFERENCES [dbo].[Wallet] ([Id])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Wallet]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
ON DELETE SET NULL
GO
USE [master]
GO
ALTER DATABASE [StockAccounts] SET  READ_WRITE 
GO
